
CREATE TABLE [dbo].[ChangeTrackingTablesToExport](
	[Id] bigint NOT NULL IDENTITY,
	[TenantCode] [varchar](100) NOT NULL,
	[SchemaName] [varchar](100) NOT NULL,
	[TableName] [varchar](100) NOT NULL,
	[PrimaryKey] [varchar](1000) NOT NULL,
	[DateAdded] [smalldatetime] NULL,
	[EnabledForExport] [varchar](20) NOT NULL,
 CONSTRAINT [PK_ChangeTrackingTablesToExport] PRIMARY KEY CLUSTERED 
(
	ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER AUTHORIZATION ON [dbo].[ChangeTrackingTablesToExport] TO  SCHEMA OWNER 

ALTER TABLE [dbo].[ChangeTrackingTablesToExport] ADD  CONSTRAINT [DF_ChangeTrackingTablesToExport_SchemaName]  DEFAULT ('dbo') FOR [SchemaName]


ALTER TABLE [dbo].[ChangeTrackingTablesToExport] ADD  CONSTRAINT [DF_ChangeTrackingTablesToExport_DateAdded]  DEFAULT (getdate()) FOR [DateAdded]

ALTER TABLE [dbo].[ChangeTrackingTablesToExport] ADD  CONSTRAINT [DF_ChangeTrackingTablesToExport_EnabledForExport]  DEFAULT ('pending') FOR [EnabledForExport]
	 

GO


CREATE TABLE [dbo].[ChangeTrackingVersion](
	[Id] bigint NOT NULL IDENTITY,
	[TablesToExportId] bigint NOT NULL,
	[LastSuccessfulRunVersionId] [bigint] NOT NULL,
	[LastExportDate] [datetime] NOT NULL,
 CONSTRAINT [PK_ChangeTrackingVersion] PRIMARY KEY CLUSTERED 
(
	Id ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ChangeTrackingVersion] ADD  CONSTRAINT [DF_LastExportDate]  DEFAULT (getdate()) FOR [LastExportDate]

ALTER TABLE [dbo].[ChangeTrackingVersion]
ADD CONSTRAINT FK_ChangeTrackingVersion_TablesToExportId FOREIGN KEY (TablesToExportId) 
REFERENCES [dbo].[ChangeTrackingTablesToExport]([Id])
	ON DELETE CASCADE
	ON UPDATE CASCADE;



GO

CREATE OR ALTER PROC [dbo].[ChangeTracking_GetChangedTables]
AS

-- this script gets a list of tables that have changed data since the last export
-- it also incudes tables for which changes have never been exported

declare @CurrentVersion BIGINT
SELECT @CurrentVersion  = CHANGE_TRACKING_CURRENT_VERSION() 

DROP TABLE IF EXISTS #tablesWithChanges
CREATE TABLE #tablesWithChanges(TableId bigint, SchemaName varchar(100), TableName varchar(100), PrimaryKey varchar(1000), LastSuccessfulRunVersionId bigint)


DECLARE @SQL NVARCHAR(MAX) = N'INSERT INTO #tablesWithChanges(TableId, SchemaName, TableName, PrimaryKey, LastSuccessfulRunVersionId)'

	SELECT @SQL = @SQL + CONCAT('SELECT distinct ', '''' + CAST(t.Id as varchar(20)) + ''' as SchemaName,', '''' + t.SchemaName + ''' as SchemaName,', '''' + t.TableName + ''' as TableName,'
	, '''' + t.PrimaryKey + ''' as PrimaryKey,'
	, LastSuccessfulRunVersionId
	,'as LastSuccessfulRunVersionId	FROM    CHANGETABLE(CHANGES [', t.SchemaName + '].[', t.TableName, '] ,', LastSuccessfulRunVersionId,') AS CT 
				 WHERE (SELECT MAX(v) FROM (VALUES(ct.SYS_CHANGE_VERSION),(ct.SYS_CHANGE_CREATION_VERSION)) as VALUE(v) ) <=', @CurrentVersion,
				' 
				UNION ALL ')
				
	FROM dbo.ChangeTrackingVersion v
	JOIN dbo.ChangeTrackingTablesToExport t ON t.Id = v.TablesToExportId AND t.EnabledForExport = 'enabled'

	
	SET @SQL = @SQL +  '
	SELECT  t.Id, t.SchemaName, t.TableName, t.PrimaryKey, 0 as LastSuccessfulRunVersionId
	FROM    dbo.ChangeTrackingVersion v
	RIGHT JOIN dbo.ChangeTrackingTablesToExport t ON t.Id = v.TablesToExportId 
	WHERE v.LastSuccessfulRunVersionId IS NULL
	'

	print @sql
    EXEC sp_ExecuteSQL @SQL


	declare @finalTableSQL nvarchar(max)
	SET @finalTableSQL = 'SELECT t.*, @CurrentVersion as CurrentVersion
	                      FROM    #tablesWithChanges t JOIN sys.tables st
						  ON t.TableName = st.name AND t.SchemaName = schema_name(st.schema_id)  
						  ORDER BY t.SchemaName, t.TableName '
	
	EXEC sp_ExecuteSQL @finalTableSQL, N'@CurrentVersion bigint', @CurrentVersion = @CurrentVersion


GO

-- these are the tables that will be exported. sample insert statement provided for reference.
insert into [dbo].[ChangeTrackingTablesToExport](TenantCode, SchemaName, TableName, PrimaryKey)
values('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContactAddress', 'ContactAddressKey')
, ('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContactSalutation', 'ContactSalutationKey')
, ('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContactMain', 'ContactKey')
,('REPLACE_WITH_TENANT_CODE', 'dbo', 'DocumentMain', 'DocumentKey')

-- here we list out all tables in IMIS database. Uncomment tables you want to export.
/*
insert into [dbo].[ChangeTrackingTablesToExport](TenantCode, SchemaName, TableName, PrimaryKey)
values('REPLACE_WITH_TENANT_CODE', 'dbo', 'AccessArea', 'PK_AccessArea'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AccessItem', 'PK_AccessItem'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AccessMain', 'PK_AccessMain'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AccountAlerts', 'PK_AccountAlerts'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AccountingMethodRef', 'PK_AccountingMethodRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AccountPending', 'PK_AccountPending'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AclPermissionTypeRef', 'PK_AclPermissionTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ActionPlan', 'PK_ActionPlan'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Activity', 'PK_Activity'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Activity_Attach', 'PK_Activity_Attach'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AdAdjustment', 'PK_AdAdjustment'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AddressCategoryPreferences', 'PK_AddressCategoryPreferences'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AddressCategoryRef', 'PK_AddressCategoryRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AddressFormatRef', 'PK_AddressFormatRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AddressMain', 'PK_AddressMain'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AddressPurposeContactType', 'PK_AddressPurposeContactType'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AddressPurposeRef', 'PK_AddressPurposeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AddressStatusRef', 'PK_AddressStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AddressToUse', 'PK_AddressToUse'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AddressTypeRef', 'PK_AddressTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AdIssueDate', 'PK_AdIssueDate'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Admin_Section_Ref', 'PK_Admin_Section_Ref'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Admin_Security', 'PK_Admin_Security'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AdSize', 'PK_AdSize'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AdvertiserAgencyMap', 'PK_AdvertiserAgencyMap'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AdvertiserRepTerritoryMap', 'PK_AdvertiserRepTerritoryMap'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AppealMain', 'PK_AppealMain'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AppealParticipation', 'PK_AppealParticipation'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AppealProduct', 'PK_AppealProduct'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AppealStatusRef', 'PK_AppealStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AsiGPSMeasureRef', 'PK_AsiGPSMeasureRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AsiNrdsAssociation', 'PK_AsiNrdsAssociation'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AsiNrdsMember', 'PK_AsiNrdsMember'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AsiNrdsMemberDemographic', 'PK_AsiNrdsMemberDemographic'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AsiNrdsMemberDesignation', 'PK_AsiNrdsMemberDesignation'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AsiNrdsMemberEducation', 'PK_AsiNrdsMemberEducation'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AsiNrdsMemberFinancial', 'PK_AsiNrdsMemberFinancial'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AsiNrdsMemberSupplemental', 'PK_AsiNrdsMemberSupplemental'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AsiNrdsOffice', 'PK_AsiNrdsOffice'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AsiNrdsOfficeSupplemental', 'PK_AsiNrdsOfficeSupplemental'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'aspnet_Applications', 'PK__aspnet_Applicati__305F8527'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'aspnet_Membership', 'PK__aspnet_Membershi__455AA20D'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'aspnet_Paths', 'PK__aspnet_Paths__63DF292D'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'aspnet_PersonalizationAllUsers', 'PK__aspnet_Personali__69980283'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'aspnet_PersonalizationPerUser', 'PK__aspnet_Personali__6C746F2E'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'aspnet_Profile', 'PK__aspnet_Profile__5A55BEF3'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'aspnet_SchemaVersions', 'PK__aspnet_SchemaVer__3ADD139A'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'aspnet_Users', 'PK__aspnet_Users__35243A44'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AsyncStatusMonitor', 'PK_AsyncStatusMonitor'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AtomPanel', 'PK_AtomPanel'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AtomPanelFactoryStateRef', 'PK_AtomPanelFactoryStateRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AtomPanelPurposeRef', 'PK_AtomPanelPurposeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AtomPanelStatusRef', 'PK_AtomPanelStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AtomPanelTemplate', 'PK_AtomPanelTemplate'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AtomPanelTemplateTypeRef', 'PK_AtomPanelTemplateTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AtomPanelTypeRef', 'PK_AtomPanelTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AtomPanelWebsite', 'PK_AtomPanelWebsite'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AuthorizationProvider', 'PK_AuthorizationProvider'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AutoPayAccount', 'PK_AutoPayAccount'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AutoPayInstruction', 'PK_AutoPayInstruction'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'AVSBillingLog', 'PK_AVSBillingLog'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'BadAddressReasonRef', 'PK_BadAddressReasonRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Basket_Function', 'PK_Basket_Function'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Basket_Meeting', 'PK_Basket_Meeting'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Basket_Payment', 'PK_Basket_Payment'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Batch', 'PK_Batch'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'BatchActionRef', 'PK_BatchActionRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'BatchLineStatusRef', 'PK_BatchLineStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'BatchSetup', 'PK_BatchSetup'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'BatchStatusRef', 'PK_BatchStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'BillingIssueNotificationLog', 'PK_BillingIssueNotificationLog'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'BillingIssueNotificationLogDetail', 'PK_BillingIssueNotificationLogDetail'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'BillingLog', 'PK_BillingLog'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'BillingLogItem', 'PK_BillingLogItem'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CalculatedEngagementScore', 'PK_CalculatedEngagementScore'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Campaign', 'PK_Campaign'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CampaignMain', 'PK_CampaignMain'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CampaignParticipation', 'PK_CampaignParticipation'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CampaignStatusRef', 'PK_CampaignStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CampaignTypeRef', 'PK_CampaignTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Cart', 'PK_Cart'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CartBilling', 'PK_CartBilling'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CartEvent', 'PK_CartEvent'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CartEventFunction', 'PK_CartEventFunction'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CartItem', 'PK_CartItem'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CartOrder', 'PK_CartOrder'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Cash_Accounts', 'PK_Cash_Accounts'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CCAuthAcct', 'PK_CCAuthAcct'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Cert_Comp_Cat', 'PK_Cert_Comp_Cat'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Cert_Prog_Lines', 'PK_Cert_Prog_Lines'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Cert_Program', 'PK_Cert_Program'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Cert_Register', 'PK_Cert_Register'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CertificationModule', 'PK_CertificationModule'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CertificationModuleGrade', 'PK_CertificationModuleGrade'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CertificationModuleProduct', 'PK_CertificationModuleProduct'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CertificationModuleRegistration', 'PK_CertificationModuleRegistration'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CertificationModuleStatusRef', 'PK_CertificationModuleStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CertificationProgram', 'PK_CertificationProgram'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CertificationProgramCertificationModule', 'PK_CertificationProgramCertificationModule'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CertificationProgramProduct', 'PK_CertificationProgramProduct'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CertificationProgramRegistration', 'PK_CertificationProgramRegistration'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CertificationProgramRegistrationCertificationModule', 'PK_CertificationProgramRegistrationCertificationModule'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ChangeLog', 'PK_ChangeLog'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ChangeProperty', 'PK_ChangeProperty'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ChangeTrackingTablesToExport', 'PK_ChangeTrackingTablesToExport'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ChangeTrackingVersion', 'PK_ChangeTrackingVersion'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CheckCategoryRef', 'PK_CheckCategoryRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ClientApplications', 'PK_ClientApplications'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CM5MigrationVariableMapping', 'PK_CM5MigrationVariableMapping'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Cmty_Administrators', 'PK_Cmty_Administrators'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Cmty_Discussion_Forums', 'PK_Cmty_Discussion_Forums'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Cmty_Discussion_Posts', 'PK_Cmty_Discussion_Posts'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Cmty_Email_Notification', 'PK_Cmty_Email_Notification'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Cmty_Invitees', 'PK_Cmty_Invitees'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Cmty_News', 'PK_Cmty_News'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Cmty_Read_Tracking', 'PK_Cmty_Read_Tracking'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Cmty_Shared_Files', 'PK_Cmty_Shared_Files'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Cmty_Shared_Folders', 'PK_Cmty_Shared_Folders'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Cmty_Subscription', 'PK_Cmty_Subscription'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Comment_Log', 'PK_Comment_Log'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CommissionRateTypeRef', 'PK_CommissionRateTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Committee_Minutes', 'PK_Committee_Minutes'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CommunicationLog', 'PK_CommunicationLog'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CommunicationLogAttachment', 'PK_CommunicationLogAttachment'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CommunicationLogEvent', 'PK_CommunicationLogEvent'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CommunicationLogEventTypeRef', 'PK_CommunicationLogEventTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CommunicationLogRecipient', 'PK_CommunicationLogRecipient'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CommunicationLogRecipientAttachment', 'PK_CommunicationLogRecipientAttachment'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CommunicationLogStatusRef', 'PK_CommunicationLogStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CommunicationMessageTypeRef', 'PK_CommunicationMessageTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CommunicationReasonRef', 'PK_CommunicationReasonRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CompanyNaicsSic', 'PK_CompanyNaicsSic'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ComparisonRef', 'PK_ComparisonRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Component_Email', 'PK_Component_Email'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Component_Email_Variable_Ref', 'PK_Component_Email_Variable_Ref'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Component_Interest_Category', 'PK_Component_Interest_Category'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Component_Interest_Group', 'PK_Component_Interest_Group'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Component_Ref', 'PK_Component_Ref'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Component_Script_Ref', 'PK_Component_Script_Ref'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ComponentCategoryRef', 'PK_ComponentCategoryRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ComponentRegistry', 'PK_ComponentRegistry'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ComponentRegistryCategory', 'PK_ComponentRegistryCategory'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ConsumableToken', 'PK_ConsumableToken'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ConsumableTokenBatch', 'PK_ConsumableTokenBatch'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ConsumableTokenScope', 'PK_ConsumableTokenScope'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContactBiography', 'PK_ContactBiography'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContactCommunicationReasonPreferences', 'PK_ContactCommunicationReasonPreferences'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContactCountHistory', 'PK_ContactCountHistory'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContactDeleteLog', 'PK_ContactDeleteLog'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContactDuplicateCheckFormula', 'PK_ContactDuplicateCheckFormula'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContactDuplicateCheckFormulaTypeRef', 'PK_ContactDuplicateCheckFormulaTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContactEducation', 'PK_ContactEducation'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContactFundraising', 'PK_ContactFundraising'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContactGiftAidDeclaration', 'PK_ContactGiftAidDeclaration'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContactInteraction', 'PK_ContactInteraction'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContactLog', 'PK_ContactLog'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContactOffering', 'PK_ContactOffering'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContactOfferingRef', 'PK_ContactOfferingRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContactPicture', 'PK_ContactPicture'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Contacts', 'PK_Contacts'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContactSkill', 'PK_ContactSkill'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContactSkillRef', 'PK_ContactSkillRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContactSocialNetwork', 'PK_ContactSocialNetwork'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContactStatusRef', 'PK_ContactStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContactTypeRef', 'PK_ContactTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContentChangeRequest', 'PK_ContentChangeRequest'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContentFilter', 'PK_ContentFilter'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContentHtmlEntitySymbolRef', 'PK_ContentHtmlEntitySymbolRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContentManagerAuthorityGroup', 'PK_ContentManagerAuthorityGroup'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContentUserDefinedFieldValue', 'PK_ContentUserDefinedFieldValue'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ContentWorkflowParameters', 'PK_ContentWorkflowParameters'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CostMethodRef', 'PK_CostMethodRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CostTier', 'PK_CostTier'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Counter', 'PK_Counter'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Country_Addr_Layouts', 'PK_Country_Addr_Layouts'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Country_Names', 'PK_Country_Names'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CountryRef', 'PK_CountryRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CreditInvoiceExport', 'PK_CreditInvoiceExport'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CreditInvoiceExportItem', 'PK_CreditInvoiceExportItem'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CreditTypeRef', 'PK_CreditTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CultivatingFor', 'PK_CultivatingFor'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CultivationActivity', 'PK_CultivationActivity'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CultureRef', 'PK_CultureRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CustomerExperience', 'PK_CustomerExperience'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CustomerExperienceStatusChange', 'PK_CustomerExperienceStatusChange'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CustomerExperienceStatusRef', 'PK_CustomerExperienceStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'CustomTabFields', 'PK_CustomTabFields'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Data_Type_Ref', 'PK_Data_Type_Ref'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DataServerCache', 'PK_DataServerCache'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DataTypeRef', 'PK_DataTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DataVaultAttempt', 'PK_DataVaultAttempt'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DataVaultAttemptSettlementStatusRef', 'PK_DataVaultAttemptSettlementStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DataVaultAttemptStatusRef', 'PK_DataVaultAttemptStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DataVaultLog', 'PK_DataVaultLog'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DataVaultLogDetail', 'PK_DataVaultLogDetail'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DataVaultStatusRef', 'PK_DataVaultStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DateDimension', 'PK_DateDimension'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DayOfTheWeekRef', 'PK_DayOfTheWeekRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Deferral_Matrix', 'PK_Deferral_Matrix'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DeferredConversionWork', 'PK_DeferredConversionWork'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DeferredIncomeWork', 'PK_DeferredIncomeWork'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DeploymentPackageRef', 'PK_DeploymentPackageRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DocumentStatusRef', 'PK_DocumentStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DocumentStorage', 'PK_DocumentStorage'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DocumentTypeRef', 'PK_DocumentTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Donation_Premium', 'PK_Donation_Premium'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DonationPremiumRule', 'PK_DonationPremiumRule'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DonationPremiumRuleGift', 'PK_DonationPremiumRuleGift'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DonationPremiumRuleSourceCode', 'PK_DonationPremiumRuleSourceCode'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DonationPremiumSet', 'PK_DonationPremiumSet'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DonationPremiumSetProduct', 'PK_DonationPremiumSetProduct'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'dtproperties', 'pk_dtproperties'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DuesCycles', 'PK_DuesCycles'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DuesImportPackagePartyError', 'PK_DuesImportPackagePartyError'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DuesImportPackagePartyMessageTypeRef', 'PK_DuesImportPackagePartyMessageTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DuesImportPackageStatusRef', 'PK_DuesImportPackageStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DuesImportPackageTask', 'PK_DuesImportPackageTask'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DuesImportStagingActivity', 'PK_DuesImportStagingActivity'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DuesImportStagingName', 'PK_DuesImportStagingName'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DuesImportStagingPayment', 'PK_DuesImportStagingPayment'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DuesImportStagingPaymentApplicationDetail', 'PK_DuesImportStagingPaymentApplicationDetail'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DuesImportStagingSubscriptions', 'PK_DuesImportStagingSubscriptions'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DuesImportStagingTrans', 'PK_DuesImportStagingTrans'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DuplicateEngineCandidate', 'PK_DuplicateEngineCandidate'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DuplicateEngineRuleSet', 'PK_DuplicateEngineRuleSet'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DuplicateNonDuplicateParty', 'PK_DuplicateNonDuplicateParty'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DuplicateParty', 'PK_DuplicateParty'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DuplicateRuleSet', 'PK_DuplicateRuleSet'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'DynamicGroup', 'PK_DynamicGroup'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'EducationInProgress', 'PK_EducationInProgress'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'EducationLevelRef', 'PK_EducationLevelRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Email_Contact', 'PK_Email_Contact'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'EngagementCategory', 'PK_EngagementCategory'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'EngagementCategoryContact', 'PK_EngagementCategoryContact'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'EngagementPercentile', 'PK_EngagementPercentile'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'EngagementScore', 'PK_EngagementScore'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Error', 'PK_Error'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'EventDetails', 'PK_EventDetails'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'EventGuest', 'PK_EventGuest'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'EventRegistrant', 'PK_EventRegistrant'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'EventRegistrationAnswer', 'PK_EventRegistrationAnswer'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'EventRelatedFunction', 'PK_EventRelatedFunction'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'EventSetupFunctionGroup', 'PK_EventSetupFunctionGroup'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'EventSetupGeneral', 'PK_EventSetupGeneral'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'EventSetupGroup', 'PK_EventSetupGroup'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'EventSetupGuest', 'PK_EventSetupGuest'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'EventSetupLabel', 'PK_EventSetupLabel'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'EventSetupQuestion', 'PK_EventSetupQuestion'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'EventSetupQuestionChoice', 'PK_EventSetupQuestionChoice'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'EventSetupRegistrant', 'PK_EventSetupRegistrant'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ExecutionModeRef', 'PK_ExecutionModeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Exhb_Meet', 'PK_Exhb_Meet'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ExperienceDefinition', 'PK_ExperienceDefinition'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ExperienceDefinitionStatusRef', 'PK_ExperienceDefinitionStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ExperienceUnit', 'PK_ExperienceUnit'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ExpiredMemberUpdateDetailLog', 'PK_ExpiredMemberUpdateDetailLog'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ExpiredMemberUpdateLog', 'PK_ExpiredMemberUpdateLog'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Expo_Reg_Class', 'PK_Expo_Reg_Class'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ExpoCad_Prod', 'PK_ExpoCad_Prod'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ExportType', 'PK_ExportType'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'FieldDesign', 'PK_FieldDesign'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'FieldSection', 'PK_FieldSection'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'File_Type_Ref', 'PK_File_Type_Ref'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'FileTypeRef', 'PK_FileTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'FinancialEntityDueTo', 'PK_FinancialEntityDueTo'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'FinancialEntityGLAccount', 'PK_FinancialEntityGLAccount'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'FirstPaymentDateTypeRef', 'PK_FirstPaymentDateTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'FormApprovalSubmission', 'PK_FormApprovalSubmission'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'FormApprovalSubmissionDetails', 'PK_FormApprovalSubmissionDetails'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'FormDefinition', 'PK_FormDefinition'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'FormDefinitionField', 'PK_FormDefinitionField'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'FormDefinitionSection', 'PK_FormDefinitionSection'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'FormDesignerLayout', 'PK_FormDesignerLayout'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'FormDesignerLibrary', 'PK_FormDesignerLibrary'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'FormDesignerType', 'PK_FormDesignerType'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'FormResponse', 'PK_FormResponse'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'FormResponseField', 'PK_FormResponseField'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Freight_Rate', 'PK_Freight_Rate'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'FullAddress', 'PK_FullAddress'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'FunctionRef', 'PK_FunctionRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Fund', 'PK_Fund'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'FundFamilyRef', 'PK_FundFamilyRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'FundFundType', 'PK_FundFundType'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'FundraisingPreferenceRef', 'PK_FundraisingPreferenceRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'FundTypeRef', 'PK_FundTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GatewayAccountLink', 'PK_GatewayAccountLink'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GatewayResultRef', 'PK_GatewayResultRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GatewayTransaction', 'PK_GatewayTransaction'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GatewayTransactionRef', 'PK_GatewayTransactionRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GatewayTypeRef', 'PK_GatewayTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Gen_Descriptions', 'PK_Gen_Descriptions'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Gen_Tables', 'PK_Gen_Tables'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Generic', 'PK_Generic'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GenericLink', 'PK_GenericLink'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GiftAdjustmentLog', 'PK_GiftAdjustmentLog'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GiftAdjustmentLogDetail', 'PK_GiftAdjustmentLogDetail'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GiftAidClaim', 'PK_GiftAidClaim'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GiftAidClaimDetail', 'PK_GiftAidClaimDetail'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GiftAidClaimStatusLog', 'PK_GiftAidClaimStatusLog'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GiftAidClaimStatusRef', 'PK_GiftAidClaimStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GiftAidMethodOfDeclarationRef', 'PK_GiftAidMethodOfDeclarationRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GiftHistorySummary', 'PK_GiftHistorySummary'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GiftTransaction', 'PK_GiftTransaction'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GLEntryTypeRef', 'PK_GLEntryTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GLExport', 'PK_GLExport'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GLExportDeferredIncomeItem', 'PK_GLExportDeferredIncomeItem'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GLExportFormatTypeRef', 'PK_GLExportFormatTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GLExportItem', 'PK_GLExportItem'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GLExportSummaryLevelRef', 'PK_GLExportSummaryLevelRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GLSourceItemTypeRef', 'PK_GLSourceItemTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GLTransactionMain', 'PK_GLTransactionMain'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GradeRef', 'PK_GradeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GroupInstanceRole', 'PK_GroupInstanceRole'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GroupMain', 'PK_GroupMain'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GroupMember', 'PK_GroupMember'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GroupMemberAdministratorTypeRef', 'PK_GroupMemberAdministratorTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GroupMemberDetail', 'PK_GroupMemberDetail'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GroupMemberOptions', 'PK_GroupMemberOptions'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GroupMemberStatusRef', 'PK_GroupMemberStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GroupOpportunityType', 'PK_GroupOpportunityType'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GroupPerspective', 'PK_GroupPerspective'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GroupPriceSheet', 'PK_GroupPriceSheet'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GroupRoleRef', 'PK_GroupRoleRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GroupStatusRef', 'PK_GroupStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GroupTypeMemberStatus', 'PK_GroupTypeMemberStatus'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GroupTypeRef', 'PK_GroupTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GroupTypeRole', 'PK_GroupTypeRole'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GroupUpdateInstruction', 'PK_GroupUpdateInstruction'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'GroupUpdateTermTypeRef', 'PK_GroupUpdateTermTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'HandlingPriceRef', 'PK_HandlingPriceRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'HIControlTypeRef', 'PK_HIControlTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Hierarchy', 'PK_Hierarchy'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'HierarchyRoot', 'PK_HierarchyRoot'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'History', 'PK_History'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'IMISTable', 'PK_IMISTable'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ImportBatch', 'PK_ImportBatch'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ImportBatchLog', 'PK_ImportBatchLog'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ImportBatchStatusRef', 'PK_ImportBatchStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ImportFileTypeRef', 'PK_ImportFileTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Individual', 'PK_Individual'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Input_Type_Ref', 'PK_Input_Type_Ref'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Institute', 'PK_Institute'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'InstituteTypeRef', 'PK_InstituteTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'InteractionAction', 'PK_InteractionAction'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'InteractionType', 'PK_InteractionType'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'InteractionTypeAction', 'PK_InteractionTypeAction'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Interest_Category', 'PK_Interest_Category'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'IntervalTypeRef', 'PK_IntervalTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'InventoryTransactionLogCost', 'PK_InventoryTransactionLogCost'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'InventoryTransactionLogLine', 'PK_InventoryTransactionLogLine'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'InventoryTransactionLogMain', 'PK_InventoryTransactionLogMain'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Invoice', 'PK_Invoice'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Invoice_Lines', 'PK_Invoice_Lines'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Invoice_Payment_Schedule', 'PK_Invoice_Payment_Schedule'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'InvoicePurposeRef', 'PK_InvoicePurposeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'InvoiceTypeRef', 'PK_InvoiceTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Iso_Currency_Codes', 'PK_Iso_Currency_Codes'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ItemClassRef', 'PK_ItemClassRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Job_Record', 'PK_Job_Record'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'JournalEntryTypeRef', 'PK_JournalEntryTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'LegacySecurityLevelRef', 'PK_LegacySecurityLevelRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'LicenseLegacyList', 'PK_LicenseLegacyList'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'LicenseRef', 'PK_LicenseRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'LinePricingRef', 'PK_LinePricingRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ListItem', 'PK_ListItem'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ListMain', 'PK_ListMain'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'LocaleRef', 'PK_LocaleRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'LocalizationApplication', 'PK_LocalizationApplication'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'LocalizationControlProperty', 'PK_LocalizationControlProperty'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'LocalizationControlType', 'PK_LocalizationControlType'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'LocalizationCulture', 'PK_LocalizationCulture'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'LocalizationLookup', 'PK_LocalizationLookup'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'LocalizationPhrase', 'PK_LocalizationPhrase'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'LocalizationPhraseTranslated', 'PK_LocalizationPhraseTranslated'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'LocalizationStatus', 'PK_LocalizationStatus'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'LocalizationVersion', 'PK_LocalizationVersion'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'LocalizationVersionPhrase', 'PK_LocalizationVersionPhrase'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'LocalizationVersionPhraseTransfer', 'PK_LocalizationVersionPhraseTransfer'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Location', 'PK_Location'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'LocationStatusRef', 'PK_LocationStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'LoginToken', 'PK_LoginToken'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Mail_Lists', 'PK_Mail_Lists'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MailCodeRef', 'PK_MailCodeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MatchingGift', 'PK_MatchingGift'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MatchingGiftPlan', 'PK_MatchingGiftPlan'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MatchingGiftPlanFundType', 'PK_MatchingGiftPlanFundType'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MatchingGiftPlanRelationship', 'PK_MatchingGiftPlanRelationship'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MatchingGiftPlanRule', 'PK_MatchingGiftPlanRule'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MatchingGiftPlanTypeRef', 'PK_MatchingGiftPlanTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MatchingModeRef', 'PK_MatchingModeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MatchingPeriodRef', 'PK_MatchingPeriodRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MediaAdTypeRef', 'PK_MediaAdTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MediaAsset', 'PK_MediaAsset'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MediaAssetGroup', 'PK_MediaAssetGroup'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MediaColorRef', 'PK_MediaColorRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MediaFrequencyRef', 'PK_MediaFrequencyRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MediaInventoryDetail', 'PK_MediaInventoryDetail'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MediaInventoryMaster', 'PK_MediaInventoryMaster'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MediaOrder', 'PK_MediaOrder'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MediaOrderBuy', 'PK_MediaOrderBuy'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MediaOrderLine', 'PK_MediaOrderLine'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MediaOrderProductionDetail', 'PK_MediaOrderProductionDetail'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MediaOrderRep', 'PK_MediaOrderRep'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MediaOrderSignedDocuments', 'PK_MediaOrderSignedDocuments'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MediaPositionRef', 'PK_MediaPositionRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MediaProductionStageRef', 'PK_MediaProductionStageRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MediaProductionStatusRef', 'PK_MediaProductionStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MediaRep', 'PK_MediaRep'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MediaSeparationRef', 'PK_MediaSeparationRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MediaTerritory', 'PK_MediaTerritory'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MediaTypeRef', 'PK_MediaTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Meet_Hotel', 'PK_Meet_Hotel'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Meet_Master', 'PK_Meet_Master'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Meet_Reg_Class', 'PK_Meet_Reg_Class'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Meet_Resources', 'PK_Meet_Resources'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Meet_Std_Resrc', 'PK_Meet_Std_Resrc'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Member_Types', 'PK_Member_Types'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MemberTypeProduct', 'PK_MemberTypeProduct'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MemorialTribute', 'PK_MemorialTribute'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MemorialTributeCodeRef', 'PK_MemorialTributeCodeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MemorialTributeNotificationMember', 'PK_MemorialTributeNotificationMember'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MethodSetTypeRef', 'PK_MethodSetTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'MonthRef', 'PK_MonthRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Name', 'PK_Name'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Name_Address', 'PK_Name_Address'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Name_AlternateId', 'PK_Name_AlternateId'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Name_Annuity', 'PK_Name_Annuity'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Name_Estates', 'PK_Name_Estates'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Name_Fin', 'PK_Name_Fin'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Name_FR', 'PK_Name_FR'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Name_FRAdditionalInfo', 'PK_Name_FRAdditionalInfo'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Name_FREventInformation', 'PK_Name_FREventInformation'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Name_FRSurveyQuestion', 'PK_Name_FRSurveyQuestion'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Name_FRTeamInformation', 'PK_Name_FRTeamInformation'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Name_FRTransactionLog', 'PK_Name_FRTransactionLog'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Name_Note', 'PK_Name_Note'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Name_Picture', 'PK_Name_Picture'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Name_PL_Pref', 'PK_Name_PL_Pref'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Name_PlannedGiving', 'PK_Name_PlannedGiving'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Name_Research', 'PK_Name_Research'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Name_Salutation', 'PK_Name_Salutation'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Name_Security', 'PK_Name_Security'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Name_Security_Groups', 'PK_Name_Security_Groups'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'NavigationExport', 'PK_NavigationExport'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'NavigationLegacySecurityRolesExport', 'PK_NavigationLegacySecurityRolesExport'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'NavigationMain', 'PK_NavigationMain'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'NavigationPaneRef', 'PK_NavigationPaneRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'NavigationSecurityGroupsExport', 'PK_NavigationSecurityGroupsExport'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'NavigationSecurityRolesExport', 'PK_NavigationSecurityRolesExport'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'NavigationWorkflowParameters', 'PK_NavigationWorkflowParameters'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Note', 'PK_Note'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'NotePurposeRef', 'PK_NotePurposeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'NotificationSet', 'PK_NotificationSet'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'NotificationSetDetail', 'PK_NotificationSetDetail'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ObjectMetaData', 'PK_ObjectMetaData'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ObjectMetaDataRelatedEntityRef', 'PK_ObjectMetaDataRelatedEntityRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ObjectPropertyMetaData', 'PK_ObjectPropertyMetaData'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OfferedCustomerExperience', 'PK_OfferedCustomerExperience'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Offering', 'PK_Offering'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OfferingStatusRef', 'PK_OfferingStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OpenIDProvider', 'PK_OpenIDProvider'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OpportunityClassRef', 'PK_OpportunityClassRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OpportunityCompetitor', 'PK_OpportunityCompetitor'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OpportunityDefaultStatusRef', 'PK_OpportunityDefaultStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OpportunityHistory', 'PK_OpportunityHistory'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OpportunityMain', 'PK_OpportunityMain'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OpportunityMainDonor', 'PK_OpportunityMainDonor'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OpportunityMainMember', 'PK_OpportunityMainMember'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OpportunityMainSales', 'PK_OpportunityMainSales'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OpportunityStatusRef', 'PK_OpportunityStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OpportunityType', 'PK_OpportunityType'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Order_Badge', 'PK_Order_Badge'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Order_Lines', 'PK_Order_Lines'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Order_Meet', 'PK_Order_Meet'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Order_Payments', 'PK_Order_Payments'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Order_Type', 'PK_Order_Type'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OrderAnswer', 'PK_OrderAnswer'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OrderCategory', 'PK_OrderCategory'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OrderCategoryParentLookup', 'PK_OrderCategoryParentLookup'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OrderCheckout', 'PK_OrderCheckout'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OrderFulfillmentStatusRef', 'PK_OrderFulfillmentStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OrderPickLine', 'PK_OrderPickLine'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OrderProduct', 'PK_OrderProduct'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OrderProductCategoryLookup', 'PK_OrderProductCategoryLookup'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OrderProductCrossSellLookup', 'PK_OrderProductCrossSellLookup'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OrderPromotion', 'PK_OrderPromotion'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OrderPromotionDiscount', 'PK_OrderPromotionDiscount'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OrderPromotionRequiredPurchaseItem', 'PK_OrderPromotionRequiredPurchaseItem'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Orders', 'PK_Orders'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Orders_VAT', 'PK_Orders_VAT'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OrderStageProcessingNotificationLog', 'PK_OrderStageProcessingNotificationLog'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OrderStageProcessingNotificationLogDetail', 'PK_OrderStageProcessingNotificationLogDetail'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OrderStateRef', 'PK_OrderStateRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OrderSuperProductAttribute', 'PK_OrderSuperProductAttribute'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OrderSuperProductAttributeLookup', 'PK_OrderSuperProductAttributeLookup'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OrderSuperProductAttributeValue', 'PK_OrderSuperProductAttributeValue'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OrderSuperProductChildProduct', 'PK_OrderSuperProductChildProduct'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OrderSuperProductChildProductAttribute', 'PK_OrderSuperProductChildProductAttribute'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Org_Control', 'PK_Org_Control'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Organization_Demo', 'PK_Organization_Demo'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OrganizationMain', 'PK_OrganizationMain'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OrganizationMergeChildren', 'PK_OrganizationMergeChildren'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OrgControlImages', 'PK_OrgControlImages'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'OutboundCommunicationStatusRef', 'PK_OutboundCommunicationStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PackageItem', 'PK_PackageItem'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PackageLogStatusRef', 'PK_PackageLogStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PackageMain', 'PK_PackageMain'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PackageQueue', 'PK_PackageQueue'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PackageQueueReleaseTypeRef', 'PK_PackageQueueReleaseTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PackageStatusRef', 'PK_PackageStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PanelDefinition', 'PK_PanelDefinition'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PaperSizeRef', 'PK_PaperSizeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PartyMergeSchemaReference', 'PK_PartyMergeSchemaReference'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PasswordHistory', 'PK_PasswordHistory'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Payment', 'PK_Payment'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PaymentAccountApplicationRestriction', 'PK_PaymentAccountApplicationRestriction'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PaymentApplicationDetail', 'PK_PaymentApplicationDetail'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PaymentApplicationRestrictionRef', 'PK_PaymentApplicationRestrictionRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PaymentApplicationTypeRef', 'PK_PaymentApplicationTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PaymentCategoryRef', 'PK_PaymentCategoryRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PaymentDetailStatusRef', 'PK_PaymentDetailStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PaymentMain', 'PK_PaymentMain'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PaymentMethodSet', 'PK_PaymentMethodSet'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PaymentMethodSetDetail', 'PK_PaymentMethodSetDetail'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PaymentStatusRef', 'PK_PaymentStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PaymentTerms', 'PK_PaymentTerms'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PaymentTermsCustomLine', 'PK_PaymentTermsCustomLine'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Perspective', 'PK_Perspective'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PhysicalAddress', 'PK_PhysicalAddress'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Picture', 'PK_Picture'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PicturePurposeRef', 'PK_PicturePurposeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Pipeline', 'PK_Pipeline'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PipelineStage', 'PK_PipelineStage'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PostalCodeRef', 'PK_PostalCodeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PotentialMatchingGift', 'PK_PotentialMatchingGift'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PrefixRef', 'PK_PrefixRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PriceBasisRef', 'PK_PriceBasisRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PriceSheet', 'PK_PriceSheet'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PricingTypeRef', 'PK_PricingTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ProcessEngineType', 'PK_ProcessEngineType'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Prod_Label_Pref', 'PK_Prod_Label_Pref'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Product', 'PK_Product'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Product_Cat', 'PK_Product_Cat'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Product_Cert', 'PK_Product_Cert'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Product_Function', 'PK_Product_Function'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Product_Instance', 'PK_Product_Instance'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Product_Inventory', 'PK_Product_Inventory'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Product_Kit', 'PK_Product_Kit'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Product_Lot', 'PK_Product_Lot'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Product_Price', 'PK_Product_Price'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Product_Sub', 'PK_Product_Sub'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Product_Trans', 'PK_Product_Trans'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Product_Type', 'PK_Product_Type'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ProductStatusRef', 'PK_ProductStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ProductTransDetail', 'PK_ProductTransDetail'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Profile_Page', 'PK_Profile_Page'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ProfileDocuments', 'PK_ProfileDocuments'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Program', 'PK_Program'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ProgramGroup', 'PK_ProgramGroup'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ProgramGroupStatusRef', 'PK_ProgramGroupStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ProgramStatusRef', 'PK_ProgramStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PromotionRuleRef', 'PK_PromotionRuleRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PropertyDefinition', 'PK_PropertyDefinition'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Prospect', 'PK_Prospect'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PublishMessageLog', 'PK_PublishMessageLog'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PublishPriorityRef', 'PK_PublishPriorityRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PublishRequest', 'PK_PublishRequest'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PublishRequestDetail', 'PK_PublishRequestDetail'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PublishRequestStatusRef', 'PK_PublishRequestStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'PublishServerRef', 'PK_PublishServerRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'QualityRef', 'PK_QualityRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'QueryResultMain', 'PK_QueryResultMain'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'RateCard', 'PK_RateCard'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'RateCardDetail', 'PK_RateCardDetail'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ReceiptLine', 'PK_ReceiptLine'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ReceiptMain', 'PK_ReceiptMain'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ReceiptStatusRef', 'PK_ReceiptStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ReceiptTypeRef', 'PK_ReceiptTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'RecurringDonationCommitment', 'PK_RecurringDonationCommitment'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'RecurringDonationExpectedPayment', 'PK_RecurringDonationExpectedPayment'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'RecurringDonationExpectedPaymentSet', 'PK_RecurringDonationExpectedPaymentSet'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'RecurringDonationExpectedPaymentSetStatusRef', 'PK_RecurringDonationExpectedPaymentSetStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'RecurringDonationExpectedPaymentStatusRef', 'PK_RecurringDonationExpectedPaymentStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'RecurringDonationFrequencyRef', 'PK_RecurringDonationFrequencyRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'RecurringDonationMatchStatusRef', 'PK_RecurringDonationMatchStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'RedirectRule', 'PK_RedirectRule'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Ref_Client', 'PK_Ref_Client'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Ref_Table_Ref', 'PK_Ref_Table_Ref'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Referral', 'PK_Referral'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'RegistrationStatusChange', 'PK_RegistrationStatusChange'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'RegistrationStatusRef', 'PK_RegistrationStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Relationship', 'PK_Relationship'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Relationship_Types', 'PK_Relationship_Types'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'RelationshipCategoryRef', 'PK_RelationshipCategoryRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'RelationshipMain', 'PK_RelationshipMain'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'RelationshipTypeCategory', 'PK_RelationshipTypeCategory'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'RelationshipTypeRef', 'PK_RelationshipTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Report_Desc', 'PK_Report_Desc'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'RepTerritory', 'PK_RepTerritory_RepTerritoryId'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Request_Status_Ref', 'PK_Request_Status_Ref'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ResponseMediaRef', 'PK_ResponseMediaRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ResponseTypeRef', 'PK_ResponseTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'RestockPriceRef', 'PK_RestockPriceRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'RFMDefinition', 'PK_RFMDefinition'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'RFMDefinition_Detail', 'PK_RFMDefinition_Detail'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'RFMMain', 'PK_RFMMain'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'RoleMain', 'PK_RoleMain'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'RoundingMultipleRef', 'PK_RoundingMultipleRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'RuleCriterion', 'PK_RuleCriterion'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'RuleFilter', 'PK_RuleFilter'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'RuleMain', 'PK_RuleMain'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SalesHistory', 'PK_SalesHistory'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SalesHistoryMemorialTribute', 'PK_SalesHistoryMemorialTribute'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SalesHistoryRelationshipTypeRef', 'PK_SalesHistoryRelationshipTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SalesHistorySoftCredit', 'PK_SalesHistorySoftCredit'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SalesLocationStatusRef', 'PK_SalesLocationStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SalutationRef', 'PK_SalutationRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ScheduledTask', 'PK_ScheduledTask'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ScheduledTaskHistory', 'PK_ScheduledTaskHistory'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ScheduledTaskService', 'PK_ScheduledTaskService'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ScheduleFrequencyRef', 'PK_ScheduleFrequencyRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ScoreComponent', 'PK_ScoreComponent'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ScreenResolutionRef', 'PK_ScreenResolutionRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Search_Requests', 'PK_Search_Requests'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SeasonalFullAddress', 'PK_SeasonalFullAddress'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Security_Filters', 'PK_Security_Filters'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Security_Group_Rule', 'PK_Security_Group_Rule'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Security_Group_Sync', 'PK_Security_Group_Sync'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Security_Groups', 'PK_Security_Groups'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Security_Modes', 'PK_Security_Modes'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SegmentationJob', 'PK_SegmentationJob'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SegmentationJobStatusRef', 'PK_SegmentationJobStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SegmentDefinition', 'PK_SegmentDefinition'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SequenceCounter', 'PK_SequenceCounter'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Service_Request', 'PK_Service_Request'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ServiceStatusRef', 'PK_ServiceStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ShipPriceRef', 'PK_ShipPriceRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SocialNetworkLinks', 'PK_SocialNetworkLinks'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SocialNetworkRef', 'PK_SocialNetworkRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SoftCreditRelationshipType', 'PK_SoftCreditRelationshipType'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SolicitationMain', 'PK_SolicitationMain'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SolicitationSource', 'PK_SolicitationSource'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SolicitationStatusRef', 'PK_SolicitationStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SortNameAdjustment', 'PK_SortNameAdjustment'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SortNameAdjustmentActionRef', 'PK_SortNameAdjustmentActionRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SourceCode', 'PK_SourceCode'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SourceCodeStatusRef', 'PK_SourceCodeStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SourceCodeTypeRef', 'PK_SourceCodeTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'StandardPageRef', 'PK_StandardPageRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'State_Codes', 'PK_State_Codes'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'StateProvinceRef', 'PK_StateProvinceRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Style_Options', 'PK_Style_Options'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Sub_Component_Ref', 'PK_Sub_Component_Ref'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Subscriptions', 'PK_Subscriptions'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SuffixRef', 'PK_SuffixRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SupplementMain', 'PK_SupplementMain'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SupplementStatusRef', 'PK_SupplementStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SupplementTypeRef', 'PK_SupplementTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'System_Params', 'PK_System_Params'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'System_Variable', 'PK_System_Variable'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SystemConfig', 'PK_SystemConfig'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SystemConfigPageParameterRef', 'PK_SystemConfigPageParameterRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SystemConfigPageRef', 'PK_SystemConfigPageRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SystemConfigParameterRef', 'PK_SystemConfigParameterRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SystemConfigXml', 'PK_SystemConfigXml'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SystemEntity', 'PK_SystemEntity'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SystemLog', 'PK_SystemLog'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SystemLogCategoryRef', 'PK_SystemLogCategoryRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SystemLogLevelRef', 'PK_SystemLogLevelRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SystemObjectTypeRef', 'PK_SystemObjectTypeCode'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SystemRef', 'PK_SystemRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'SystemTypeRef', 'PK_SystemTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Tag', 'PK_Tag'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TagRelatedName', 'PK_TagRelatedName'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TagRelationship', 'PK_TagRelationship'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TagRelationshipTypeRef', 'PK_TagRelationshipTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaskActionLog', 'PK_TaskActionLog'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaskActionLogAttachment', 'PK_TaskActionLogAttachment'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaskActionLogDetail', 'PK_TaskActionLogDetail'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaskCommonTableRef', 'PK_TaskCommonTableRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaskDefinition', 'PK_TaskDefinition'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaskItem', 'PK_TaskItem'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaskItemStatusRef', 'PK_TaskItemStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaskLog', 'PK_TaskLog'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaskLogDetail', 'PK_TaskLogDetail'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaskMain', 'PK_TaskMain'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaskNotifyCreatorRef', 'PK_TaskNotifyCreatorRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaskPriorityRef', 'PK_TaskPriorityRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaskQueue', 'PK_TaskQueue'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaskQueueAdvancedEmailEventDetail', 'PK_TaskQueueAdvancedEmailEventDetail'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaskQueueAdvancedEmailSendDetail', 'PK_TaskQueueAdvancedEmailSendDetail'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaskQueueChangeTypeRef', 'PK_TaskQueueChangeTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaskQueuePublishDetail', 'PK_TaskQueuePublishDetail'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaskQueueStatusRef', 'PK_TaskQueueStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaskQueueTriggerDetail', 'PK_TaskQueueTriggerDetail'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaskQueueTypeRef', 'PK_TaskQueueTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaskStatusRef', 'PK_TaskStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaskTypeRef', 'PK_TaskTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaxAuthorityCategory', 'PK_TaxAuthorityCategory'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaxAuthorityFinancialEntity', 'PK_TaxAuthorityFinancialEntity'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaxAuthorityLevelRef', 'PK_TaxAuthorityLevelRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaxCategory', 'PK_TaxCategory'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TaxScheduleAuthority', 'PK_TaxScheduleAuthority'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Terms', 'PK_Terms'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Theme', 'PK_Theme'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TimeZoneRef', 'PK_TimeZoneRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Trans', 'PK_Trans'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Trans_SoftCredit', 'PK_Trans_SoftCredit'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TransactionTypeRef', 'PK_TransactionTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'TransTaskQueue', 'PK_TransTaskQueue'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'UniformDistribution', 'PK_UniformDistribution'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'UniformLicense', 'PK_UniformLicense'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'UniformLink', 'PK_UniformLink'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'UniformRegistry', 'PK_UniformRegistry'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'UniformTag', 'PK_UniformTag'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'UniformTypeRef', 'PK_UniformTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'UnofferedCustomerExperience', 'PK_UnofferedCustomerExperience'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'UpgradeLog', 'PK_UpgradeLog'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'UpgradeLogDetail', 'PK_UpgradeLogDetail'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'URLMapping', 'PK_URLMapping'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'URLMappingTypeRef', 'PK_URLMappingTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'UsedSourceCode', 'PK_UsedSourceCode'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'User_Tab_Pref', 'PK_User_Tab_Pref'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'User_Tab_Pref_Detail', 'PK_User_Tab_Pref_Detail'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'UserDefinedCustomerExperience', 'PK_UserDefinedCustomerExperience'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'UserDefinedFieldRef', 'PK_UserDefinedFieldRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'UserMain', 'PK_UserMain'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'UserRole', 'PK_UserRole'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Users', 'PK_Users'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'UserToken', 'PK_UserToken'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Variable_Type_Ref', 'PK_Variable_Type_Ref'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Vat_Rule_Set', 'PK_Vat_Rule_Set'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'VAT_Trans', 'PK_VAT_Trans'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'VerticalAlignmentRef', 'PK_VerticalAlignmentRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'VolunteerAvailability', 'PK_VolunteerAvailability'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'VolunteerHistory', 'PK_VolunteerHistory'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'VolunteerInformation', 'PK_VolunteerInformation'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'VolunteersInterests', 'PK_VolunteersInterests'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'VolunteerSkills', 'PK_VolunteerSkills'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'WarehouseCarrier', 'PK_WarehouseCarrier'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'WarehouseStatusRef', 'PK_WarehouseStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'WarehouseTypeRef', 'PK_WarehouseTypeRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Web_Counter', 'PK_Web_Counter'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Website', 'PK_Website'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'WebUserControlRef', 'PK_WebUserControlRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Workflow_Status_Ref', 'PK_Workflow_Status_Ref'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'WorkflowDemoLog', 'PK_WorkflowDemoLog'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'WorkflowInstance', 'PK_WorkflowInstance'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'WorkflowQueue', 'PK_WorkflowQueue'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'WorkflowQueueStatusRef', 'PK_WorkflowQueueStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'WorkflowService', 'PK_WorkflowService'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'WorkflowServiceWorker', 'PK_WorkflowServiceWorker'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'WorkflowStatusRef', 'PK_WorkflowStatusRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'WorkInvoiceMain', 'PK_WorkInvoiceMain'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'WorkItem', 'PK_WorkItem'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'WorkItemQueue', 'PK_WorkItemQueue'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'WorkOrderMain', 'PK_WorkOrderMain'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'YearRef', 'PK_YearRef'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Zip_Code', 'PK_Zip_Code'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'Zip3', 'PK_Zip3'),
('REPLACE_WITH_TENANT_CODE', 'dbo', 'ZipCodeRef', 'PK_ZipCodeRef')


*/